"""Exact H3 spinor construction of the regular 600-cell.

The thirty H3 roots are derived as normalized edge-midpoint directions of the
exact icosahedron.  Ordered even Clifford products of those roots generate the
120 unit spinors of the binary icosahedral group, interpreted as the vertices
of the regular 600-cell in four-dimensional Euclidean space.

This module establishes a finite geometric bridge.  It does not identify the
600-cell with physical spacetime, a universe, or a literal Omniverse.
"""

from __future__ import annotations

from collections import Counter
from functools import cache
from itertools import combinations

from .platonic_solid_bridge import (
    ONE,
    PHI,
    ZERO,
    Coordinate,
    PhiNumber,
    cross,
    dot,
    solid_edges,
)
from .twenty_four_cell_bridge import TWENTY_FOUR_CELL_VERTICES

Coordinate4D = tuple[PhiNumber, PhiNumber, PhiNumber, PhiNumber]
Edge4D = tuple[Coordinate4D, Coordinate4D]
Triangle4D = tuple[Coordinate4D, Coordinate4D, Coordinate4D]
Tetrahedron4D = tuple[Coordinate4D, Coordinate4D, Coordinate4D, Coordinate4D]

SIX_HUNDRED_CELL_EDGE_SQUARED = PhiNumber(2, -1)


def _coordinate_key(coordinate: tuple[PhiNumber, ...]) -> tuple[float, ...]:
    return tuple(float(component) for component in coordinate)


def _normalized_icosahedral_edge_midpoints() -> tuple[Coordinate, ...]:
    scale = ONE / (2 * PHI)
    roots = {
        tuple((left[axis] + right[axis]) * scale for axis in range(3))
        for left, right in solid_edges("icosahedron")
    }
    return tuple(sorted(roots, key=_coordinate_key))


H3_ROOTS = _normalized_icosahedral_edge_midpoints()
_H3_ROOT_SET = frozenset(H3_ROOTS)


def h3_reflect(vector: Coordinate, root: Coordinate) -> Coordinate:
    """Reflect one H3 root in the plane normal to another H3 root."""
    if vector not in _H3_ROOT_SET or root not in _H3_ROOT_SET:
        raise ValueError("vector and root must both belong to the H3 root system")
    scale = 2 * dot(vector, root) / dot(root, root)
    reflected = tuple(vector[axis] - scale * root[axis] for axis in range(3))
    if reflected not in _H3_ROOT_SET:
        raise RuntimeError("H3 reflection escaped the root system")
    return reflected


def _spinor_product(left: Coordinate, right: Coordinate) -> Coordinate4D:
    return (*cross(left, right), dot(left, right))


SIX_HUNDRED_CELL_VERTICES = tuple(
    sorted(
        {_spinor_product(left, right) for left in H3_ROOTS for right in H3_ROOTS},
        key=_coordinate_key,
    )
)
_SIX_HUNDRED_CELL_VERTEX_SET = frozenset(SIX_HUNDRED_CELL_VERTICES)


def h3_spinor_product(left: Coordinate, right: Coordinate) -> Coordinate4D:
    """Return the unit 4D spinor generated by an ordered pair of H3 roots."""
    if left not in _H3_ROOT_SET or right not in _H3_ROOT_SET:
        raise ValueError("both inputs must belong to the H3 root system")
    spinor = _spinor_product(left, right)
    if spinor not in _SIX_HUNDRED_CELL_VERTEX_SET:
        raise RuntimeError("H3 spinor product escaped the 600-cell")
    return spinor


def dot4(left: Coordinate4D, right: Coordinate4D) -> PhiNumber:
    """Return the exact 4D Euclidean dot product."""
    return sum((a * b for a, b in zip(left, right, strict=True)), ZERO)


def squared_distance4(left: Coordinate4D, right: Coordinate4D) -> PhiNumber:
    """Return exact squared distance in the 600-cell coordinate field."""
    difference = tuple(a - b for a, b in zip(left, right, strict=True))
    return dot4(difference, difference)


def central_mirror_4d(coordinate: Coordinate4D) -> Coordinate4D:
    """Reflect one 4D coordinate through the shared center."""
    if len(coordinate) != 4:
        raise ValueError("coordinate must have exactly four components")
    return tuple(-component for component in coordinate)


def quaternion_product(left: Coordinate4D, right: Coordinate4D) -> Coordinate4D:
    """Multiply spinors in vector-scalar quaternion coordinates ``(XYZ, W)``."""
    if left not in _SIX_HUNDRED_CELL_VERTEX_SET or right not in _SIX_HUNDRED_CELL_VERTEX_SET:
        raise ValueError("both inputs must be 600-cell spinors")
    left_vector, left_scalar = left[:3], left[3]
    right_vector, right_scalar = right[:3], right[3]
    vector_cross = cross(left_vector, right_vector)
    vector = tuple(
        left_scalar * right_vector[axis] + right_scalar * left_vector[axis] + vector_cross[axis]
        for axis in range(3)
    )
    product = (*vector, left_scalar * right_scalar - dot(left_vector, right_vector))
    if product not in _SIX_HUNDRED_CELL_VERTEX_SET:
        raise RuntimeError("quaternion multiplication escaped the binary icosahedral group")
    return product


HURWITZ_24_CELL_VERTICES = tuple(
    sorted(
        {
            tuple(PhiNumber(component) / 2 for component in vertex)
            for vertex in TWENTY_FOUR_CELL_VERTICES
        },
        key=_coordinate_key,
    )
)
SNUB_24_CELL_VERTICES = tuple(
    vertex
    for vertex in SIX_HUNDRED_CELL_VERTICES
    if vertex not in frozenset(HURWITZ_24_CELL_VERTICES)
)


def pure_h3_spinors() -> tuple[Coordinate4D, ...]:
    """Return the W=0 H3 root subsystem embedded in the 600-cell."""
    return tuple(vertex for vertex in SIX_HUNDRED_CELL_VERTICES if vertex[3] == ZERO)


@cache
def six_hundred_cell_edges() -> tuple[Edge4D, ...]:
    """Derive all 720 edges at the regular edge distance."""
    return tuple(
        (left, right)
        for left, right in combinations(SIX_HUNDRED_CELL_VERTICES, 2)
        if squared_distance4(left, right) == SIX_HUNDRED_CELL_EDGE_SQUARED
    )


@cache
def _neighbor_map() -> dict[Coordinate4D, frozenset[Coordinate4D]]:
    neighbors = {vertex: set() for vertex in SIX_HUNDRED_CELL_VERTICES}
    for left, right in six_hundred_cell_edges():
        neighbors[left].add(right)
        neighbors[right].add(left)
    return {vertex: frozenset(adjacent) for vertex, adjacent in neighbors.items()}


def _canonical_simplex(vertices) -> tuple[Coordinate4D, ...]:
    return tuple(sorted(vertices, key=_coordinate_key))


@cache
def six_hundred_cell_triangular_faces() -> tuple[Triangle4D, ...]:
    """Derive the 1,200 triangular cliques of the edge graph."""
    neighbors = _neighbor_map()
    faces = {
        frozenset((vertex, left, right))
        for vertex in SIX_HUNDRED_CELL_VERTICES
        for left, right in combinations(neighbors[vertex], 2)
        if right in neighbors[left]
    }
    return tuple(
        sorted(
            (_canonical_simplex(face) for face in faces),
            key=lambda face: tuple(map(_coordinate_key, face)),
        )
    )


@cache
def six_hundred_cell_tetrahedral_cells() -> tuple[Tetrahedron4D, ...]:
    """Derive the 600 tetrahedral 3-cells as four-vertex edge cliques."""
    neighbors = _neighbor_map()
    cells = set()
    for face in six_hundred_cell_triangular_faces():
        shared = neighbors[face[0]] & neighbors[face[1]] & neighbors[face[2]]
        cells.update(frozenset((*face, vertex)) for vertex in shared)
    return tuple(
        sorted(
            (_canonical_simplex(cell) for cell in cells),
            key=lambda cell: tuple(map(_coordinate_key, cell)),
        )
    )


def vertex_cell_incidence_counts() -> tuple[int, ...]:
    """Return the number of tetrahedral cells incident on each vertex."""
    counts = Counter(vertex for cell in six_hundred_cell_tetrahedral_cells() for vertex in cell)
    return tuple(counts[vertex] for vertex in SIX_HUNDRED_CELL_VERTICES)


if len(H3_ROOTS) != 30:
    raise RuntimeError("the icosahedral edge directions must generate exactly 30 H3 roots")
if any(dot(root, root) != ONE for root in H3_ROOTS):
    raise RuntimeError("all H3 roots must be exactly unit normalized")
if len(SIX_HUNDRED_CELL_VERTICES) != 120:
    raise RuntimeError("H3 spinors must generate exactly 120 600-cell vertices")
if any(dot4(vertex, vertex) != ONE for vertex in SIX_HUNDRED_CELL_VERTICES):
    raise RuntimeError("all 600-cell vertices must lie on the exact unit 3-sphere")
if not set(HURWITZ_24_CELL_VERTICES) <= _SIX_HUNDRED_CELL_VERTEX_SET:
    raise RuntimeError("the existing 24-cell must embed in the 600-cell")
