"""Electrostatic-like interaction observable for the 3D U(1) Matrix adapter.

This module derives the minimum quadratic field energy compatible with a
specified lattice charge density. It does NOT insert a Coulomb 1/r potential.

Given the discrete Gauss constraint

    div(E) = rho,

the minimum-energy longitudinal field can be written

    E_i(x) = phi(x) - phi(x+e_i),

where phi solves the periodic discrete Poisson equation

    L phi = rho

with

    L phi(x) = sum_i [2 phi(x) - phi(x+e_i) - phi(x-e_i)].

On a periodic lattice the zero Fourier mode is removed, so every source density
is interpreted together with its uniform neutralizing background unless it is
already neutral.

The resulting field energy

    U = 1/2 sum_links E_i^2

provides an interaction observable generated by the gauge constraint itself.
"""

from __future__ import annotations

from dataclasses import dataclass
import math
from typing import Iterable

import numpy as np

try:
    from .gauge_3d import AXES
except ImportError:
    from gauge_3d import AXES


@dataclass(frozen=True)
class Source:
    position: tuple[int, int, int]
    charge: float


@dataclass
class ElectrostaticSolution:
    charge_density: np.ndarray
    potential: np.ndarray
    electric: dict[str, np.ndarray]
    energy: float

    def gauss_residual(self) -> np.ndarray:
        shape = self.charge_density.shape
        div = np.zeros(shape, dtype=float)
        for axis_index, axis in enumerate(AXES):
            e = self.electric[axis]
            div += e - np.roll(e, 1, axis=axis_index)
        return div - self.charge_density

    def max_abs_gauss_residual(self) -> float:
        return float(np.max(np.abs(self.gauss_residual())))


def charge_density(
    shape: tuple[int, int, int],
    sources: Iterable[Source],
    neutralize_zero_mode: bool = True,
) -> np.ndarray:
    """Construct a periodic charge density.

    When neutralize_zero_mode=True, subtract the spatial mean. This is required
    for a periodic Poisson solution and represents a uniform compensating
    background for a non-neutral finite cell.
    """
    if any(n <= 1 for n in shape):
        raise ValueError("each dimension must be at least 2")
    rho = np.zeros(shape, dtype=float)
    for source in sources:
        idx = tuple(source.position[i] % shape[i] for i in range(3))
        rho[idx] += source.charge
    if neutralize_zero_mode:
        rho -= float(np.mean(rho))
    elif not math.isclose(float(np.sum(rho)), 0.0, abs_tol=1e-14):
        raise ValueError("periodic Poisson problem requires zero total charge")
    return rho


def poisson_eigenvalues(shape: tuple[int, int, int]) -> np.ndarray:
    """Eigenvalues of the positive periodic lattice Laplacian L."""
    grids = np.meshgrid(
        *[np.arange(n, dtype=float) for n in shape],
        indexing="ij",
    )
    lam = np.zeros(shape, dtype=float)
    for grid, n in zip(grids, shape):
        lam += 4.0 * np.sin(np.pi * grid / n) ** 2
    return lam


def solve_minimum_energy_field(rho: np.ndarray) -> ElectrostaticSolution:
    """Solve L phi=rho spectrally and return the minimum-energy field."""
    if rho.ndim != 3:
        raise ValueError("rho must be a 3D array")
    if any(n <= 1 for n in rho.shape):
        raise ValueError("each dimension must be at least 2")

    total = float(np.sum(rho))
    if not math.isclose(total, 0.0, abs_tol=1e-12):
        raise ValueError("rho must have zero total charge")

    lam = poisson_eigenvalues(rho.shape)
    rho_k = np.fft.fftn(rho)
    phi_k = np.zeros_like(rho_k, dtype=complex)

    mask = lam > 1e-15
    phi_k[mask] = rho_k[mask] / lam[mask]
    phi_k[~mask] = 0.0

    phi = np.fft.ifftn(phi_k).real

    electric = {}
    for axis_index, axis in enumerate(AXES):
        electric[axis] = phi - np.roll(phi, -1, axis=axis_index)

    energy = 0.5 * sum(float(np.sum(e * e)) for e in electric.values())

    return ElectrostaticSolution(
        charge_density=np.array(rho, copy=True),
        potential=phi,
        electric=electric,
        energy=energy,
    )


def solve_sources(
    shape: tuple[int, int, int],
    sources: Iterable[Source],
    neutralize_zero_mode: bool = True,
) -> ElectrostaticSolution:
    rho = charge_density(shape, sources, neutralize_zero_mode)
    return solve_minimum_energy_field(rho)


def pair_energy(
    shape: tuple[int, int, int],
    separation: int,
    charge_a: float = 1.0,
    charge_b: float = -1.0,
    axis: int = 0,
) -> float:
    """Minimum field energy for two localized sources at a given separation."""
    if axis not in (0, 1, 2):
        raise ValueError("axis must be 0, 1, or 2")
    if separation <= 0:
        raise ValueError("separation must be positive")
    p0 = [0, 0, 0]
    p1 = [0, 0, 0]
    p1[axis] = separation
    return solve_sources(
        shape,
        [
            Source(tuple(p0), charge_a),
            Source(tuple(p1), charge_b),
        ],
        neutralize_zero_mode=True,
    ).energy


def discrete_radial_force(
    shape: tuple[int, int, int],
    separation: int,
    charge_a: float = 1.0,
    charge_b: float = -1.0,
    axis: int = 0,
) -> float:
    """Central finite-difference force proxy F_r = -dU/dr in lattice units."""
    if separation <= 1:
        raise ValueError("separation must exceed 1 for central difference")
    u_minus = pair_energy(shape, separation - 1, charge_a, charge_b, axis)
    u_plus = pair_energy(shape, separation + 1, charge_a, charge_b, axis)
    return -0.5 * (u_plus - u_minus)


def interaction_energy_cross_term(
    shape: tuple[int, int, int],
    source_a: Source,
    source_b: Source,
) -> float:
    """Extract the pair cross-term U_ab from quadratic field energy.

    Each single-source cell uses the same zero-mode neutralization convention.
    """
    both = solve_sources(shape, [source_a, source_b]).energy
    ua = solve_sources(shape, [source_a]).energy
    ub = solve_sources(shape, [source_b]).energy
    return both - ua - ub
