"""Minimal exact SU(3) lattice Wilson gauge prototype.

Links:
    U_i(x) in SU(3)

Local gauge transformation:
    U_i(x) -> G(x) U_i(x) G^dagger(x+i)

Plaquette:
    P_ij(x)
      = U_i(x)
        U_j(x+i)
        U_i^dagger(x+j)
        U_j^dagger(x)

Wilson action:
    S_W
      = beta * sum_p [
          1 - 1/3 Re Tr(P_p)
        ].

Random SU(3) matrices are generated by QR-unitarizing a random complex matrix
and then correcting the determinant to exactly one up to floating arithmetic.

This is a mathematical non-Abelian gauge prototype. It is not yet identified
with QCD.
"""

from __future__ import annotations

import numpy as np


AXES = (0, 1, 2)
IDENTITY3 = np.eye(3, dtype=complex)


def project_to_su3(matrix: np.ndarray) -> np.ndarray:
    """Project a nonsingular complex 3x3 matrix to SU(3) using QR."""
    z = np.asarray(matrix, dtype=complex)
    if z.shape != (3, 3):
        raise ValueError("matrix must be 3x3")

    q, r = np.linalg.qr(z)
    diagonal = np.diag(r)
    phases = np.ones(3, dtype=complex)
    nonzero = np.abs(diagonal) > 0
    phases[nonzero] = diagonal[nonzero] / np.abs(diagonal[nonzero])

    # Remove the arbitrary QR diagonal phases.
    q = q @ np.diag(np.conj(phases))

    determinant = np.linalg.det(q)
    if abs(determinant) == 0:
        raise ValueError("cannot project singular unitary candidate")
    q[:, 0] *= 1.0 / determinant
    return q


def random_su3(rng: np.random.Generator) -> np.ndarray:
    z = (
        rng.normal(size=(3, 3))
        + 1j*rng.normal(size=(3, 3))
    )
    return project_to_su3(z)


def is_su3(matrix: np.ndarray, tolerance: float = 1e-11) -> bool:
    u = np.asarray(matrix, dtype=complex)
    if u.shape != (3, 3):
        return False
    return (
        np.allclose(u.conj().T @ u, IDENTITY3, atol=tolerance, rtol=0)
        and abs(np.linalg.det(u) - 1.0) <= tolerance
    )


def identity_links(shape: tuple[int, int, int]) -> np.ndarray:
    out = np.empty((3,) + shape + (3, 3), dtype=complex)
    out[...] = IDENTITY3
    return out


def random_links(
    shape: tuple[int, int, int],
    rng: np.random.Generator,
) -> np.ndarray:
    out = np.empty((3,) + shape + (3, 3), dtype=complex)
    for axis in AXES:
        for idx in np.ndindex(shape):
            out[(axis,) + idx] = random_su3(rng)
    return out


def forward_index(
    idx: tuple[int, int, int],
    axis: int,
    shape: tuple[int, int, int],
) -> tuple[int, int, int]:
    out = list(idx)
    out[axis] = (out[axis] + 1) % shape[axis]
    return tuple(out)


def plaquette(
    links: np.ndarray,
    idx: tuple[int, int, int],
    i: int,
    j: int,
) -> np.ndarray:
    if i == j or i not in AXES or j not in AXES:
        raise ValueError("axes must be distinct members of {0,1,2}")

    shape = links.shape[1:4]
    xi = forward_index(idx, i, shape)
    xj = forward_index(idx, j, shape)

    return (
        links[(i,) + idx]
        @ links[(j,) + xi]
        @ links[(i,) + xj].conj().T
        @ links[(j,) + idx].conj().T
    )


def wilson_action(links: np.ndarray, beta: float = 1.0) -> float:
    if beta < 0:
        raise ValueError("beta must be non-negative")
    shape = links.shape[1:4]
    total = 0.0
    for idx in np.ndindex(shape):
        for i, j in ((0, 1), (1, 2), (2, 0)):
            p = plaquette(links, idx, i, j)
            total += 1.0 - (1.0/3.0)*float(np.trace(p).real)
    return beta*total


def gauge_transform(
    links: np.ndarray,
    site_transform: np.ndarray,
) -> np.ndarray:
    shape = links.shape[1:4]
    if site_transform.shape != shape + (3, 3):
        raise ValueError("site transform shape mismatch")

    out = np.empty_like(links)
    for axis in AXES:
        for idx in np.ndindex(shape):
            xp = forward_index(idx, axis, shape)
            out[(axis,) + idx] = (
                site_transform[idx]
                @ links[(axis,) + idx]
                @ site_transform[xp].conj().T
            )
    return out


def random_site_gauge_transform(
    shape: tuple[int, int, int],
    rng: np.random.Generator,
) -> np.ndarray:
    out = np.empty(shape + (3, 3), dtype=complex)
    for idx in np.ndindex(shape):
        out[idx] = random_su3(rng)
    return out
