"""Annular external ports for conservative junction control volumes.

This redesign preserves the conservative inlet-to-outlet transport logic of the
rectangular junction checkpoint while replacing disk-like external edge ports
with annuli. The axisymmetric field is generated by a stream function, so its
interior divergence vanishes identically and its side-wall normal flux is zero.

Each incident edge receives one full annular band. The boundary profile uses
the same cumulative flux law as the annular Piola connector, making the port
topology and flux density connector-compatible without silently changing
cross-section topology.
"""

from __future__ import annotations

import math
from collections.abc import Hashable, Sequence
from dataclasses import dataclass
from enum import StrEnum

from .graph_toroidal_flux_bundle import GraphToroidalFluxBundle
from .toroidal_connector_topology import ANNULAR_PORT, annular_connector_source_density
from .vesica_tree_circulation import DirectedCurrent

_TOLERANCE = 1e-12
Point3D = tuple[float, float, float]


def _finite(value: float, name: str) -> float:
    value = float(value)
    if not math.isfinite(value):
        raise ValueError(f"{name} must be finite")
    return value


class AnnularPortFace(StrEnum):
    LOWER = "lower"
    UPPER = "upper"


@dataclass(frozen=True)
class AnnularJunctionPort[NodeT: Hashable]:
    edge_index: int
    node: NodeT
    outward_flux: float
    face: AnnularPortFace
    inner_radius: float
    outer_radius: float
    flux_coordinate_lower: float
    flux_coordinate_upper: float

    def __post_init__(self) -> None:
        if not isinstance(self.edge_index, int) or isinstance(self.edge_index, bool):
            raise TypeError("edge_index must be an integer")
        if self.edge_index < 0:
            raise ValueError("edge_index must be nonnegative")
        for name in (
            "outward_flux",
            "inner_radius",
            "outer_radius",
            "flux_coordinate_lower",
            "flux_coordinate_upper",
        ):
            object.__setattr__(self, name, _finite(getattr(self, name), name))
        if self.inner_radius <= 0 or self.outer_radius <= self.inner_radius:
            raise ValueError("annular port radii must be positive and ordered")
        if self.flux_coordinate_lower < -_TOLERANCE:
            raise ValueError("flux coordinate must be nonnegative")
        if self.flux_coordinate_upper < self.flux_coordinate_lower - _TOLERANCE:
            raise ValueError("flux coordinate interval must be ordered")
        if not math.isclose(
            self.flux_coordinate_upper - self.flux_coordinate_lower,
            abs(self.outward_flux),
            rel_tol=0.0,
            abs_tol=_TOLERANCE,
        ):
            raise ValueError("flux coordinate interval must equal the port flux magnitude")
        if self.outward_flux > _TOLERANCE and self.face is not AnnularPortFace.UPPER:
            raise ValueError("positive outward flux must use the upper face")
        if self.outward_flux < -_TOLERANCE and self.face is not AnnularPortFace.LOWER:
            raise ValueError("negative outward flux must use the lower face")

    @property
    def topology(self):
        return ANNULAR_PORT

    @property
    def magnitude(self) -> float:
        return abs(self.outward_flux)

    @property
    def width(self) -> float:
        return self.outer_radius - self.inner_radius


@dataclass(frozen=True)
class AnnularFluxTransfer:
    inlet_edge_index: int
    outlet_edge_index: int
    flux: float

    def __post_init__(self) -> None:
        object.__setattr__(self, "flux", _finite(self.flux, "flux"))
        if self.flux <= 0:
            raise ValueError("transfer flux must be positive")


@dataclass(frozen=True)
class AnnularJunctionControlVolume[NodeT: Hashable]:
    node: NodeT
    center: Point3D
    length: float
    inner_radius: float
    outer_radius: float
    ports: tuple[AnnularJunctionPort[NodeT], ...]

    def __post_init__(self) -> None:
        if len(self.center) != 3:
            raise ValueError("center must contain three coordinates")
        object.__setattr__(
            self,
            "center",
            tuple(_finite(value, "center coordinate") for value in self.center),
        )
        for name in ("length", "inner_radius", "outer_radius"):
            object.__setattr__(self, name, _finite(getattr(self, name), name))
        if self.length <= 0:
            raise ValueError("length must be positive")
        if self.inner_radius <= 0 or self.outer_radius <= self.inner_radius:
            raise ValueError("junction annulus must have positive ordered radii")
        if len({port.edge_index for port in self.ports}) != len(self.ports):
            raise ValueError("each incident edge must have one annular port")
        if abs(self.total_outward_flux) > _TOLERANCE:
            raise ValueError("annular junction must be conservative")
        if not self.port_bands_are_disjoint():
            raise ValueError("annular port bands must be disjoint on each face")

    @staticmethod
    def _cdf(q: float) -> float:
        q = min(1.0, max(0.0, q))
        return (2.0 * q - q**2) ** 3

    @staticmethod
    def _cdf_derivative(q: float) -> float:
        if q <= 0.0 or q >= 1.0:
            return 0.0
        return 6.0 * (1.0 - q) * (2.0 * q - q**2) ** 2

    @staticmethod
    def _smoothstep(s: float) -> float:
        return 3.0 * s**2 - 2.0 * s**3

    @staticmethod
    def _smoothstep_derivative(s: float) -> float:
        return 6.0 * s * (1.0 - s)

    @property
    def total_outward_flux(self) -> float:
        return math.fsum(port.outward_flux for port in self.ports)

    @property
    def lower_ports(self) -> tuple[AnnularJunctionPort[NodeT], ...]:
        return tuple(
            sorted(
                (port for port in self.ports if port.face is AnnularPortFace.LOWER),
                key=lambda port: port.inner_radius,
            )
        )

    @property
    def upper_ports(self) -> tuple[AnnularJunctionPort[NodeT], ...]:
        return tuple(
            sorted(
                (port for port in self.ports if port.face is AnnularPortFace.UPPER),
                key=lambda port: port.inner_radius,
            )
        )

    def port_by_edge(self, edge_index: int) -> AnnularJunctionPort[NodeT]:
        try:
            return next(port for port in self.ports if port.edge_index == edge_index)
        except StopIteration as error:
            raise ValueError("edge is not incident on this annular junction") from error

    def port_bands_are_disjoint(self) -> bool:
        for face_ports in (self.lower_ports, self.upper_ports):
            if any(
                left.outer_radius > right.inner_radius + _TOLERANCE
                for left, right in zip(face_ports, face_ports[1:])
            ):
                return False
        return True

    def _face_ports(self, face: AnnularPortFace):
        return self.lower_ports if face is AnnularPortFace.LOWER else self.upper_ports

    def _face_total_magnitude(self, face: AnnularPortFace) -> float:
        return math.fsum(port.magnitude for port in self._face_ports(face))

    def face_streamfunction(self, face: AnnularPortFace, radius: float) -> float:
        radius = _finite(radius, "radius")
        ports = self._face_ports(face)
        if not ports or radius <= self.inner_radius:
            return 0.0
        total = self._face_total_magnitude(face)
        if radius >= self.outer_radius:
            return total / (2.0 * math.pi)
        for port in ports:
            if radius < port.inner_radius:
                return port.flux_coordinate_lower / (2.0 * math.pi)
            if radius <= port.outer_radius:
                q = (radius - port.inner_radius) / port.width
                cumulative = port.flux_coordinate_lower + port.magnitude * self._cdf(q)
                return cumulative / (2.0 * math.pi)
        return total / (2.0 * math.pi)

    def face_streamfunction_derivative(self, face: AnnularPortFace, radius: float) -> float:
        radius = _finite(radius, "radius")
        for port in self._face_ports(face):
            if port.inner_radius < radius < port.outer_radius:
                q = (radius - port.inner_radius) / port.width
                return (
                    port.magnitude
                    * self._cdf_derivative(q)
                    / (2.0 * math.pi * port.width)
                )
        return 0.0

    def transport_plan(self) -> tuple[AnnularFluxTransfer, ...]:
        transfers = []
        for inlet in self.lower_ports:
            if inlet.magnitude <= _TOLERANCE:
                continue
            for outlet in self.upper_ports:
                if outlet.magnitude <= _TOLERANCE:
                    continue
                lower = max(inlet.flux_coordinate_lower, outlet.flux_coordinate_lower)
                upper = min(inlet.flux_coordinate_upper, outlet.flux_coordinate_upper)
                if upper - lower > _TOLERANCE:
                    transfers.append(
                        AnnularFluxTransfer(
                            inlet.edge_index,
                            outlet.edge_index,
                            upper - lower,
                        )
                    )
        return tuple(transfers)

    def _local_point(self, point: Sequence[float]) -> Point3D:
        if len(point) != 3:
            raise ValueError("point must contain exactly three coordinates")
        values = tuple(_finite(value, "coordinate") for value in point)
        return tuple(value - center for value, center in zip(values, self.center, strict=True))

    def current(self, point: Sequence[float]) -> Point3D:
        x, y, z = self._local_point(point)
        radius = math.hypot(x, y)
        if (
            radius < self.inner_radius
            or radius > self.outer_radius
            or abs(z) > self.length / 2
        ):
            return 0.0, 0.0, 0.0
        s = (z + self.length / 2) / self.length
        h = self._smoothstep(s)
        hp = self._smoothstep_derivative(s)
        psi_lower = self.face_streamfunction(AnnularPortFace.LOWER, radius)
        psi_upper = self.face_streamfunction(AnnularPortFace.UPPER, radius)
        dpsi_lower = self.face_streamfunction_derivative(AnnularPortFace.LOWER, radius)
        dpsi_upper = self.face_streamfunction_derivative(AnnularPortFace.UPPER, radius)
        axial = ((1.0 - h) * dpsi_lower + h * dpsi_upper) / radius
        radial = -hp * (psi_upper - psi_lower) / (self.length * radius)
        return (
            radial * x / radius,
            radial * y / radius,
            axial,
        )

    def outward_normal_density(self, edge_index: int, radius: float) -> float:
        port = self.port_by_edge(edge_index)
        z = self.center[2] + (
            -self.length / 2
            if port.face is AnnularPortFace.LOWER
            else self.length / 2
        )
        point = (self.center[0] + radius, self.center[1], z)
        axial = self.current(point)[2]
        return -axial if port.face is AnnularPortFace.LOWER else axial

    def connector_profile_residual(self, edge_index: int, radius: float) -> float:
        port = self.port_by_edge(edge_index)
        measured = abs(self.outward_normal_density(edge_index, radius))
        expected = abs(
            annular_connector_source_density(
                port.magnitude,
                port.inner_radius,
                port.outer_radius,
                radius,
            )
        )
        return abs(measured - expected)

    @property
    def side_wall_flux(self) -> float:
        return 0.0


def _incident_specs[NodeT: Hashable](
    node: NodeT,
    currents: Sequence[DirectedCurrent[NodeT]],
) -> tuple[tuple[int, float, AnnularPortFace], ...]:
    specs = []
    for edge_index, edge in enumerate(currents):
        if edge.source == node:
            outward = edge.current
            zero_face = AnnularPortFace.UPPER
        elif edge.target == node:
            outward = -edge.current
            zero_face = AnnularPortFace.LOWER
        else:
            continue
        face = (
            AnnularPortFace.UPPER
            if outward > _TOLERANCE
            else AnnularPortFace.LOWER
            if outward < -_TOLERANCE
            else zero_face
        )
        specs.append((edge_index, outward, face))
    if abs(math.fsum(spec[1] for spec in specs)) > _TOLERANCE:
        raise ValueError("node incident fluxes are not conservative")
    return tuple(specs)


def _assign_face_ports[NodeT: Hashable](
    node: NodeT,
    specs: Sequence[tuple[int, float, AnnularPortFace]],
    face: AnnularPortFace,
    inner_radius: float,
    outer_radius: float,
) -> tuple[AnnularJunctionPort[NodeT], ...]:
    selected = sorted((spec for spec in specs if spec[2] is face), key=lambda spec: spec[0])
    if not selected:
        return ()
    band_width = (outer_radius - inner_radius) / len(selected)
    cumulative = 0.0
    ports = []
    for index, (edge_index, outward, _) in enumerate(selected):
        lower = inner_radius + index * band_width
        upper = inner_radius + (index + 1) * band_width
        magnitude = abs(outward)
        ports.append(
            AnnularJunctionPort(
                edge_index=edge_index,
                node=node,
                outward_flux=outward,
                face=face,
                inner_radius=lower,
                outer_radius=upper,
                flux_coordinate_lower=cumulative,
                flux_coordinate_upper=cumulative + magnitude,
            )
        )
        cumulative += magnitude
    return tuple(ports)


def build_annular_junction_control_volume[NodeT: Hashable](
    node: NodeT,
    currents: Sequence[DirectedCurrent[NodeT]],
    *,
    center: Point3D = (0.0, 0.0, 0.0),
    length: float = 1.0,
    inner_radius: float = 0.5,
    outer_radius: float = 1.5,
) -> AnnularJunctionControlVolume[NodeT]:
    length = _finite(length, "length")
    inner_radius = _finite(inner_radius, "inner_radius")
    outer_radius = _finite(outer_radius, "outer_radius")
    if length <= 0:
        raise ValueError("length must be positive")
    if inner_radius <= 0 or outer_radius <= inner_radius:
        raise ValueError("annular junction radii must be positive and ordered")
    specs = _incident_specs(node, currents)
    ports = (
        _assign_face_ports(node, specs, AnnularPortFace.LOWER, inner_radius, outer_radius)
        + _assign_face_ports(node, specs, AnnularPortFace.UPPER, inner_radius, outer_radius)
    )
    return AnnularJunctionControlVolume(
        node=node,
        center=center,
        length=length,
        inner_radius=inner_radius,
        outer_radius=outer_radius,
        ports=tuple(sorted(ports, key=lambda port: port.edge_index)),
    )


@dataclass(frozen=True)
class AnnularJunctionNetwork[NodeT: Hashable]:
    bundle: GraphToroidalFluxBundle[NodeT]
    nodes: tuple[NodeT, ...]
    junctions: tuple[AnnularJunctionControlVolume[NodeT], ...]

    def junction(self, node: NodeT) -> AnnularJunctionControlVolume[NodeT]:
        try:
            return next(junction for junction in self.junctions if junction.node == node)
        except StopIteration as error:
            raise ValueError("unknown network node") from error

    def edge_flux_residual(self) -> float:
        residuals = []
        for channel in self.bundle.channels:
            edge = channel.edge
            source = self.junction(edge.source).port_by_edge(channel.edge_index).outward_flux
            target = self.junction(edge.target).port_by_edge(channel.edge_index).outward_flux
            residuals.extend(
                (
                    abs(source - edge.current),
                    abs(target + edge.current),
                )
            )
        return max(residuals, default=0.0)

    def maximum_node_balance_residual(self) -> float:
        return max((abs(junction.total_outward_flux) for junction in self.junctions), default=0.0)

    def maximum_connector_profile_residual(self) -> float:
        residuals = []
        for junction in self.junctions:
            for port in junction.ports:
                for q in (0.1, 0.25, 0.5, 0.75, 0.9):
                    radius = port.inner_radius + port.width * q
                    residuals.append(
                        junction.connector_profile_residual(port.edge_index, radius)
                    )
        return max(residuals, default=0.0)

    def junctions_are_disjoint(self) -> bool:
        ordered = sorted(self.junctions, key=lambda junction: junction.center[0])
        return all(
            right.center[0] - left.center[0]
            >= 2.0 * left.outer_radius - _TOLERANCE
            for left, right in zip(ordered, ordered[1:])
        )


def connect_bundle_to_annular_junctions[NodeT: Hashable](
    bundle: GraphToroidalFluxBundle[NodeT],
    nodes: Sequence[NodeT],
    *,
    length: float = 1.0,
    inner_radius: float = 0.5,
    outer_radius: float = 1.5,
    junction_gap: float = 0.25,
) -> AnnularJunctionNetwork[NodeT]:
    ordered_nodes = tuple(nodes)
    if len(set(ordered_nodes)) != len(ordered_nodes):
        raise ValueError("network nodes must be unique")
    endpoints = {endpoint for edge in bundle.edges for endpoint in (edge.source, edge.target)}
    if endpoints - set(ordered_nodes):
        raise ValueError("network nodes must contain every graph endpoint")
    junction_gap = _finite(junction_gap, "junction_gap")
    if junction_gap < 0:
        raise ValueError("junction_gap must be nonnegative")
    spacing = 2.0 * outer_radius + junction_gap
    midpoint = (len(ordered_nodes) - 1) / 2
    junctions = tuple(
        build_annular_junction_control_volume(
            node,
            bundle.edges,
            center=((index - midpoint) * spacing, 0.0, 0.0),
            length=length,
            inner_radius=inner_radius,
            outer_radius=outer_radius,
        )
        for index, node in enumerate(ordered_nodes)
    )
    network = AnnularJunctionNetwork(bundle, ordered_nodes, junctions)
    if not network.junctions_are_disjoint():
        raise RuntimeError("annular junction control volumes must be disjoint")
    if network.edge_flux_residual() > _TOLERANCE:
        raise RuntimeError("annular junction edge fluxes do not match the graph currents")
    return network
